# copy.yml

- name: copy default recipe to remote server
  copy:
     src: ../../../../jenkins/scripts/chef-repo/default.rb
     dest: /home/ec2-user/chef-repo/cookbooks/nginx_setup/recipes/
     owner: ec2-user
     group: ec2-user
     mode: 0774

- name: copy webserver recipe to remote server
  copy:
     src: ../../../../jenkins/scripts/chef-repo/webserver.rb
     dest: /home/ec2-user/chef-repo/cookbooks/nginx_setup/recipes/
     owner: ec2-user
     group: ec2-user
     mode: 0774

- name: copy ERB template to remote server
  copy:
     src: ../../../../jenkins/scripts/chef-repo/nginx.conf.erb
     dest: /home/ec2-user/chef-repo/cookbooks/nginx_setup/templates/
     owner: ec2-user
     group: ec2-user
     mode: 0644
